### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by ChenyangRan** [richardrl/rlkit-relational#5]
Hi, your work is insteresting, but I meet some error when testing.
Could you please help me?
I don't know how to fix it.

Thanks.
![image](https://user-images.githubusercontent.com/29306735/77166872-f813da00-6aef-11ea-8b50-e0e7dd9e43da.png)

**Comment by richardrl** [comment]
1. Are you using Python3?
2. Did you install the fetch block construction package here? https://github.com/richardrl/fetch-block-construction

**Comment by ChenyangRan** [comment]
> 1. Are you using Python3?
> 2. Did you install the fetch block construction package here? https://github.com/richardrl/fetch-block-construction

Yes, I'm using the python3.5 and have installed this pkg.
But it still not work.
Should I change the config?
I think the model should be  'here_no_dooad'?

**Comment by richardrl** [comment]
@ChenyangRan I would assume invalid syntax is because I am using the python3 style of formatting strings.

Yes, try changing the config file, "here_no_doodad" is for running on your local machine. 

Also, try running this script and share the output: https://github.com/richardrl/fetch-block-construction/blob/master/random_test.py

**Comment by ChenyangRan** [comment]
I have tested the random_test.py, the result is as:
![图片](https://user-images.githubusercontent.com/29306735/78850739-7f4ad280-7a4a-11ea-862e-ba472e66ff7c.png)
And I find my version is 3.5, should I change update the version of python?

**Comment by richardrl** [comment]
@ChenyangRan Yes, that is your problem, python version 3.6 is the first version that supports f-strings. Try upgrading and report back.

**Comment by ChenyangRan** [comment]
> 
> 
> @ChenyangRan Yes, that is your problem, python version 3.6 is the first version that supports f-strings. Try upgrading and report back.

Thanks, I'll update.
