### ISSUE TITLE
why I the prefix in 'data' is 'test'

### ISSUE THREAD

**Issue by cww97** [richardrl/rlkit-relational#9]
[here](https://github.com/richardrl/rlkit-relational/blob/master/examples/relationalrl/train_pickandplace1.py#L287)

the example is `'train' pick and place`, why the prefix is 'test'?
a little confused from a newbie, (may a stupid question

from the code I found it is truly training with batch

**Comment by richardrl** [comment]
Hi, you can change this to whatever you want. It's just naming the results directory with a prefix.
